// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzOROI8mR1T_WTvFnmV_vLcmPne8TdkUY',
    appId: '1:740655104620:web:04942c2e043f1a271c0e49',
    messagingSenderId: '740655104620',
    projectId: 'growstore-7a9e1',
    authDomain: 'growstore-7a9e1.firebaseapp.com',
    storageBucket: 'growstore-7a9e1.firebasestorage.app',
    measurementId: 'G-Z7E3P579FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUIeaDOEcqa6_U0N7ekNczkVON8_FJQsY',
    appId: '1:740655104620:android:e3af18674331a5fe1c0e49',
    messagingSenderId: '740655104620',
    projectId: 'growstore-7a9e1',
    storageBucket: 'growstore-7a9e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRjy0kTL2mVpfqGNtUwSTB_QcaaqgWqi8',
    appId: '1:740655104620:ios:af810858815a2acc1c0e49',
    messagingSenderId: '740655104620',
    projectId: 'growstore-7a9e1',
    storageBucket: 'growstore-7a9e1.firebasestorage.app',
    iosBundleId: 'com.example.growstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRjy0kTL2mVpfqGNtUwSTB_QcaaqgWqi8',
    appId: '1:740655104620:ios:af810858815a2acc1c0e49',
    messagingSenderId: '740655104620',
    projectId: 'growstore-7a9e1',
    storageBucket: 'growstore-7a9e1.firebasestorage.app',
    iosBundleId: 'com.example.growstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzOROI8mR1T_WTvFnmV_vLcmPne8TdkUY',
    appId: '1:740655104620:web:edc50b5e5a8810581c0e49',
    messagingSenderId: '740655104620',
    projectId: 'growstore-7a9e1',
    authDomain: 'growstore-7a9e1.firebaseapp.com',
    storageBucket: 'growstore-7a9e1.firebasestorage.app',
    measurementId: 'G-08ZKGSKH12',
  );

}